<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_logoPony</name>
   <tag></tag>
   <elementGuidId>e910e111-7fb4-4a21-8692-02dee334d2e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_complete_container']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.pony_express</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c21f403-d2eb-4098-aca5-a5df2b9ce62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pony Express</value>
      <webElementGuid>785dbfc7-105b-46d7-b91c-6f06e50d0993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pony_express</value>
      <webElementGuid>7d5d2854-eae4-451d-8085-7bb93fb889a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/pony-express.46394a5d.png</value>
      <webElementGuid>c2afcea6-195c-4631-850b-60057d4a2755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_complete_container&quot;)/img[@class=&quot;pony_express&quot;]</value>
      <webElementGuid>2a633851-b27b-47a4-ac19-9ab135470faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout_complete_container']/img</value>
      <webElementGuid>2f918c03-5f00-4823-bb30-7cdf56da7781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pony Express']</value>
      <webElementGuid>854d2402-c93c-4b7f-b216-88626a07ee6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>e0713179-e791-42cf-af4d-1f6889614d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Pony Express' and @src = '/static/media/pony-express.46394a5d.png']</value>
      <webElementGuid>aef12712-caf9-4df8-aa26-e3337f75a297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
