<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_footer</name>
   <tag></tag>
   <elementGuidId>3a43a3c7-ee1e-4832-a172-2b2a405c94ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']/footer/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.footer_robot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6734cbc0-db36-4b8a-946f-4a108a22dc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Swag Bot Footer</value>
      <webElementGuid>b0ab15ed-7466-4952-a914-4aefe2e15b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_robot</value>
      <webElementGuid>e83c8b60-91c1-494b-942e-1ac555c4bdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/SwagBot_Footer_graphic.2e87acec.png</value>
      <webElementGuid>b816d859-777b-4229-bee0-18fe5f080b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)/footer[@class=&quot;footer&quot;]/img[@class=&quot;footer_robot&quot;]</value>
      <webElementGuid>7bd38675-3345-4663-aabc-d4382d13e05f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']/footer/img</value>
      <webElementGuid>bab658b4-5ce0-4c80-8aae-9937f87c052a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Swag Bot Footer']</value>
      <webElementGuid>9b95e9fa-3686-4e35-8d2d-f23702d7382d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/img</value>
      <webElementGuid>1e891014-3d2e-4864-ab17-20cfa6b2fc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Swag Bot Footer' and @src = '/static/media/SwagBot_Footer_graphic.2e87acec.png']</value>
      <webElementGuid>ec1b916f-9c78-4e6f-a68a-e60b7f84db1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
